### ISSUE TITLE
Don't prompt to reload window

### ISSUE THREAD

**Issue by letmaik** [OpenRA/vscode-openra-lua#1]
The Lua extension automatically picks up the generated files after a few seconds, so a restart isn't necessary. 

How about removing this part?
https://github.com/OpenRA/vscode-openra-lua/blob/15890b99d5fcdf6de6396f29690e2ccb430c5895/src/extension.ts#L109-L111

**Comment by Mailaender** [comment]
https://github.com/sumneko/lua-language-server/issues/648 promised this was fixed so the nag screen could go away.

**Comment by Mailaender** [comment]
Sadly this is not the case
![image](https://user-images.githubusercontent.com/756669/154154044-3ea8a4a3-01e9-4c08-a2be-a7576d8385e0.png)

**Comment by letmaik** [comment]
How odd, it really does work for me.


https://user-images.githubusercontent.com/530988/154156482-2bcffe8f-9922-4528-bec1-360374368850.mp4

**Comment by Mailaender** [comment]
Strange. Is this a Windows vs. Linux file system thing?

**Comment by letmaik** [comment]
I'm assuming it's not the filewatcher handle limitation since that should have led to a popup, but just in case:
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by Mailaender** [comment]
This was removed in https://github.com/OpenRA/vscode-openra-lua/pull/2 so let's give it a try.
