### ISSUE TITLE
Cannot assign `number` to parameter `wangle?`.

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/vscode-openra-lua#8]
![image](https://user-images.githubusercontent.com/756669/221354164-2ac9ac7d-c924-48f6-b58e-e3ba1168eeef.png)

**Comment by penev92** [comment]
Now this one is a missing feature - #7 (and https://github.com/OpenRA/OpenRA/pull/20609) forgot to define the `+` operator for `wangle`. It's a trivial fix.
